services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: backend
    container_name: backend-app
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - app/.env
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  Redis:
    container_name: redis
    image: redis:7-alpine

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-app
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql

volumes:
  mysql-data:
